### PR TITLE
Adding GAMData struct

### PR DESCRIPTION
**Pull request by yahrMason**
Working on refactoring the model functions to use struct arguments. 

I reviewed the text and got a much better understanding of how to build the penalty matrix for handling multiple smoothing terms. I now have a working example off of the trees data set that converges to a solution for the smoothing penalties.

I will look to extend this to handle generalized additive models with different link functions.

### CODE REVIEW

**Comment by yahrMason** [comment]
Still need to clean up the functions a bit by adding doc strings and perhaps better typing. Also need to add "smooth" indicators to the struct so that it can handle both smooth and non-smooth terms.

**Comment by hendersontrent** [comment]
Thanks for this! Just tested it all -- looking real nice! Turns out that having a copy of the textbook at hand is useful! Super keen to see where you get this to :)

**Comment by yahrMason** [comment]
Thanks! Your previous comments about GCV not being appropriate for models where the dependent variable follows a non-normal distribution were correct. He outlines two additional approaches in his text that handle the generalized cases. One is the random effects approach, which I think MixedModels.jl could be a good candidate for. The other is the Penalized  Iteratively Re-weighted Least Squares (PIRLS) algorithm. That looks pretty straight forward so will try my hand at implementing that.

**Comment by hendersontrent** [comment]
Yep, I am aware of the random effects/spline stuff (see https://www.tjmahr.com/random-effects-penalized-splines-same-thing/ for a great overview). If you feel confident trying PIRLS then I think we start there. May as well get something working with one less dependency for now!

**Comment by hendersontrent** [comment]
Sorry, I would contribute more but I am a bit slammed across PhD and work at the moment. Hopefully can help out more substantively soon!

**Comment by yahrMason** [comment]
No worries! I am poking away at this in the free time. Will look to make a commit soon. Probably going to have to refactor slightly, but starting to get my head wrapped about how to do this properly.

**Comment by hendersontrent** [comment]
That last commit is looking clean @yahrMason !

**Comment by yahrMason** [comment]
Thank you. Just need to update the weights calculation in the PIRLS algorithm. I think it's pretty close.

**Comment by yahrMason** [comment]
This is fairly close now. I haven't tested it out on many examples, though this gamma model returns the expected output. I want to do a little more reading on how to optimize the smoothing parameters for different distributions, I think there are better approaches when the dispersion parameter is known (Binomial, Poisson).

Another thing that might be worth considering is replacing these dictionaries for Links and Distributions with custom structs like GLM.jl does. (See [here](https://github.com/JuliaStats/GLM.jl/blob/master/src/glmtools.jl)) I think adopting a similar approach would be good for consistency across model fitting packages. We could consider adding it as a dependency, but that has it's own pros/cons. I asked ChatGPT to [mock up some examples](https://chatgpt.com/share/f57770ad-ba96-4995-a11a-08ca7f9e153c) of what this could look like.

**Comment by hendersontrent** [comment]
This is excellent. I'll take a detailed look through the code this week or next but from my cursory scan today it's extremely impressive. So sorry I haven't had any time to help you lately!

**Comment by hendersontrent** [comment]
@yahrMason is this ready for my review?

**Comment by yahrMason** [comment]
@hendersontrent its not fully complete, but its way better than current state. For example it doesn't handle non-smooth terms. But perhaps that's a different feature. I will leave it up to you how you want to proceed. I would be curious of your opinion.

**Comment by yahrMason** [comment]
To clarify my previous comment.
If you want to review the current set of functions, provide feedback, and then merge, I think that would be a fine path. Though future PRs would be needed to make it fully feature complete. 

If you would rather we continue to tinker on this PR until is more feature complete, that's also a fine path.

I don't have a preference either way.

**Comment by hendersontrent** [comment]
I think maybe I review the current set of functions, get the current state on `main` in line with this excellent work of yours. Then we can set up separate issues for all the features/bugs we want to add and fix so we can work through them systematically?

**Comment by yahrMason** [comment]
@hendersontrent sounds like a good plan 👍

**Comment by hendersontrent** [comment]
@yahrMason Looking at this properly now. Is all your substantive work in `dev/gam_dev.jl`? If so, I'll partition it all into separate scripts like I previously had in the `src` folder, just for ease of use.

**Comment by yahrMason** [comment]
That's correct. That's certainly a great idea. My julia dev chops are lacking (I use my one big script format). But I imagined you might have wanted to do that.

**Pull request merged**
